import type { Metadata } from "next";
import "./globals.css";
import ToasterWrapper from "./Components/Shared/ToastWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <ToasterWrapper />
      </body>
    </html>
  );
}
